CREATE TABLE Menu_categories(
Menu_ID INT UNSIGNED NOT NULL PRIMARY KEY,
Menu_Types VARCHAR(50) NOT NULL); 

CREATE TABLE Menu_items(
Item_ID INT UNSIGNED NOT NULL PRIMARY KEY,
Item_name VARCHAR(50) NOT NULL,
Item_price DECIMAL(2,2) NOT NULL ,
Item_category INT UNSIGNED NOT NULL, 
FOREIGN KEY(Item_category)
	REFERENCES Menu_categories(Menu_ID) ); 

 
	
CREATE TABLE Tim_store(
Shop_ID INT UNSIGNED NOT NULL PRIMARY KEY,
Shop_adress VARCHAR(50) NOT NULL );

CREATE TABLE Sales_type(
Sale_type_ID INT UNSIGNED NOT NULL PRIMARY KEY,
Sale_type VARCHAR(50) NOT NULL );

CREATE TABLE Employees(
Employee_ID INT UNSIGNED NOT NULL PRIMARY KEY,
First_name VARCHAR(50) NOT NULL,
Last_name VARCHAR(50) NOT NULL ); 

CREATE TABLE Sales_record(
Sale_ID INT UNSIGNED NOT NULL PRIMARY KEY,
Date_and_time DATETIME NOT NULL,
Sale_type INT UNSIGNED NOT NULL,
Store INT UNSIGNED NOT NULL,
Employee INT UNSIGNED NOT NULL,
FOREIGN KEY(Sale_type)
	REFERENCES Sales_type(Sale_type_ID),
FOREIGN KEY(Store)
	REFERENCES Tim_store(Shop_ID),
FOREIGN KEY(Employee)
	REFERENCES Employees(Employee_ID) );
	
CREATE TABLE line_items(
Line_item_ID INT UNSIGNED NOT NULL,
Sale_ID INT UNSIGNED NOT NULL,
Item_ID INT UNSIGNED NOT NULL,
PRIMARY KEY (Line_item_id, Sale_ID),
FOREIGN KEY (Sale_ID)
	REFERENCES Sales_record(Sale_ID),
FOREIGN KEY (Item_ID)
	REFERENCES Menu_items(Item_ID) );			 